### ISSUE TITLE
[Feature Request]: reduce the durability of the tools as much as I use them.

### ISSUE THREAD

**Issue by syano-u** [FTBTeam/FTB-Mods-Issues#1158]
### Mod

FTB Ultimine(1.19.2)

### Description

Currently, no matter how many blocks are destroyed, the durability value is only reduced by 1.
This discourages players from using stone and iron tools.

Hunger is consumed, but we would like to see a setting where destroying 20 blocks reduces the durability value by 20.

(This text was created using DeepL)

### Describe the solution you'd like

I would like to see a “Consume tool endurance for each block destroyed” item in the config.

### Describe alternatives you've considered

Of course, some people do not need this. But some people need it.

**Comment by desht** [comment]
> Currently, no matter how many blocks are destroyed, the durability value is only reduced by 1

This is not the case.  Durability is already reduced by the number of blocks broken - I just tested that and verified it.

Had a Netherite Shovel with 1843/2031 durability.  Ultimined 64 blocks, shovel now has 1779/2031 durability.

I don't know what items you're using to dig, but vanilla tools certainly behave correctly, and if some modded tool isn't consuming durability, I would raise an issue with the author or that mod, since FTB Ultimine uses standard vanilla methods for performing the dig operation, which includes applying durability damage to the tool as needed.
