### ISSUE TITLE
[Bug]: Update FTB lib

### ISSUE THREAD

**Issue by wolfieboy09** [FTBTeam/FTB-Mods-Issues#1167]
### Mod

FTB lib

### Mod version

latest FTB mods

### Forge / Fabric version

1.20.1 47.2.30

### What issue are you having?

![image](https://cdn.discordapp.com/attachments/560188834592063488/1237004393791094824/image.png?ex=663a119d&is=6638c01d&hm=aeff19bc2d4859da5d5750d4fec51d87dbc632f2e52985960f9da09a7e6489fc&)

![image](https://cdn.discordapp.com/attachments/560188834592063488/1237004393791094824/image.png?ex=663a119d&is=6638c01d&hm=aeff19bc2d4859da5d5750d4fec51d87dbc632f2e52985960f9da09a7e6489fc&)

The latest lib is not working with other FTB mods

### Steps to reproduce

1. Update the FTB mods
2. MC can't load

### Anything else to note?

Just update the liberary version to work

**Comment by desht** [comment]
Update to the latest published versions of all FTB mods for 1.20.1.

**Comment by izak-jimenez** [comment]
> Update to the latest published versions of all FTB mods for 1.20.1.

That's the actual issue, if you update to the latest version available in Curseforge for 1.20.1, which is `2001.2.1` and released on 4.22.2024, you still get an error that recommends installing version `2001.1.2` or above or below `2001.2.0`, both of which are **not** the latest version of the mod as you suggest, and consequently, cause the error mentioned by @wolfieboy09 
 
Here is an image of an instance with the latest version of FTB Library installed still getting the error:
![2024-05-08_00 47 35](https://github.com/FTBTeam/FTB-Mods-Issues/assets/8889054/02c755ad-e7c8-47b6-984e-7a4d1bd6bfc5)

So the problem here is that you cannot use the latest version because that is not supported by FTB Teams, and if you downgrade to a version between `2001.1.2` and `2001.2.0` then you run into issues with FTB Teams and FTB Quests.

**Comment by desht** [comment]
It's obvious that you haven't updated FTB Teams.  When I said "Update to the latest published versions of **all** FTB mods", I meant it.
