### ISSUE TITLE
[Bug]: FTB Questing - Updating screen events

### ISSUE THREAD

**Issue by K20510** [FTBTeam/FTB-Mods-Issues#121]
### Mod

FTB Quest

### Mod version

FTBQuests-1202.9.0.15

### Forge / Fabric version

1.12.2

### What issue are you having?

Every time I open the quest book in FTB Quests, my game crashes. 

### Crashlogs

https://pastebin.com/UNzz6FaH

### Steps to reproduce

I am not sure how to reproduce this issue. It only happens after I create quests, close Minecraft and reopen it.

**Comment by Raidobw2** [comment]
Linked to #113

**Comment by Raidobw2** [comment]
I'll keep only #113 for our mod dev to avoid redundancy, however, thank you for reporting

The only advice I can give for this issue is to use FTB Interactions' version of FTB Quests, since that one works. If that's the latest version, the issue could be the result of a mod interaction, which is only solved by doing a binary search.

That is, you'd cut the modlist in half until FTB Quest doesn't crash anymore. While cutting the modlist, keep FTB Mods in the files. Then you'd find the culprit if there is one
