### ISSUE TITLE
[Bug]: Alignment of images in quest descripiton

### ISSUE THREAD

**Issue by Alicegamergirl** [FTBTeam/FTB-Mods-Issues#1263]
### Mod

ftb quests

### Mod version

ftb-quests-forge-2001.4.7

### Forge / Fabric version

1.20.1

### What issue are you having?

example string {image:minecraft:item/stick width:16 height:16 align:1}

whether you set align to 1 or 2, the image will be centered

### Steps to reproduce

doing it in a text editor or gui editor yields the same result

**Comment by desht** [comment]
Rather than using 0, 1, or 2, use "left", "center" or "right"  E.g. `{image:minecraft:item/stick width:16 height:16 align:left}`

There is a bug here, in that the edit GUI when you right the image and select "Edit" is showing numeric values. Fixed in 1.21 already, but I will get a fix for this into 1.20.1 as well.

**Comment by desht** [comment]
Fixed in 2001.4.8
