### ISSUE TITLE
[Bug]: FTB Quests - TPS reduced when in a team with multiple members online

### ISSUE THREAD

**Issue by PolygonError** [FTBTeam/FTB-Mods-Issues#1363]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.5.9-build.399

### Forge / Fabric version

1.19.2-43.3.7

### Modpack & version

Minecraft Chocolate Edition

### What issue are you having?

FTB Quests drops TPS massively when in a FTB Team with multiple members online
The modpack includes ftb-quests-forge-1902.5.6-build.304, but this issue persists on ftb-quests-forge-1902.5.9-build.399 as well.

### Steps to reproduce

1. Create an FTB Team, invite multiple players who are online
2. Observe TPS raise and drop with the number of members online
(In my example, with a team of 4 players, when only one player is online it is 20, 2 players it will be around 17, 3 players it will be around 14, 4 players it will be around 10 TPS)

**Comment by PolygonError** [comment]
Spark shows the function ftbquests.quest.TeamData.setProgress() is the one raising and lowering TPS proportional to the number of players online

**Comment by Diamondback88** [comment]
Can confirm I can reproduce this issue

**Comment by desht** [comment]
The Spark trace suggests there's a stat task in your quest book which is being marked complete over and over (which shouldn't happen - there's a check in the code for this). I would need to see what that task is to have a chance of reproducing this issue. If you can find the task that would be great, otherwise I will need to see your quest book data (the contents of `config/ftbquests/quests`)

**Comment by Diamondback88** [comment]
If you go further into the Spark report though, ItemTask is getting checked for completion, so is it likely a stat task that is also checking for an item task somehow?

**Comment by Diamondback88** [comment]
@desht There only appear to be six quests in this modpack that check for stats; a file search for these can be found below. Of these, the only repeatable ones are the first two in temps.snbt, if that helps.

![image](https://github.com/user-attachments/assets/0c6fe7e4-0afa-4281-bc91-11a0f56c6f7d)

I've attached the entire FTB Quests folder for this modpack below.

[ftbquests.zip](https://github.com/user-attachments/files/17382007/ftbquests.zip)

**Comment by desht** [comment]
Yeah, I see the problem. Repeatable stat tasks are a huge no-no, for reason you've just discovered. This forces the stat task to complete over and over and over, every 3 ticks. And when a task completes, a task scan is done to check for other completed task, which isn't normally a problem, because tasks aren't supposed to be created that often.

```
{
                        can_repeat: true
                        id: "71205726B9342781"
                        rewards: [{
                                auto: "no_toast"
                                command: "/execute at @p in blue_skies:everdawn run particle blue_skies:star_glimmer ~ ~1 ~ 10 5 10 2 50 normal"
                                exclude_from_claim_all: true
                                id: "0C245B6219076E3F"
                                ignore_reward_blocking: true
                                silent: true
                                team_reward: false
                                type: "command"
                        }]       
                        tasks: [{       
                                id: "54D662D096636C13"
                                stat: "minecraft:walk_one_cm"
                                type: "stat"
                                value: 1
                        }]      
                        title: "Everdawn Dust particle"
                        x: 8.25d
                        y: -0.25d
                }
```
This appears to be a hack just to get a command run every few ticks? You really can't use FTB Quests to do that.

**Comment by PolygonError** [comment]
thanks for the info, we've let the modpack developers know.
