### ISSUE TITLE
[Bug]: Team '<Team name>' not found!

### ISSUE THREAD

**Issue by JustJinxed** [FTBTeam/FTB-Mods-Issues#144]
### Mod

FTB Teams

### Mod version

ftb-teams-forge-1605.2.3-build.40

### Forge / Fabric version

1.16.5 36.2.20

### Modpack & version

OceanBlock 1.10.1

### What issue are you having?

Attempting to set a flag for a team returns an error: Team '<Team name>' not found!

/ftbteams server settings TeamID ftbchunks:allow_fake_players true
We're attempting to add a new island nearby other players and set their team up without having to leave or destroy our admin team (which only has a single player in it) and since the create island command seems to be restricted to only players who aren't in a team, we were hoping to add a fake player to it, so the admin can hop out, create an island and hop back into his original team. 

Can you you also advise how we would create an island for a new player? 

### Crashlogs

No crash

### Steps to reproduce

/ftbteams server settings TeamID ftbchunks:allow_fake_players true

**Comment by JustJinxed** [comment]
Side note, after leaving a team, trying to rejoin it also results in "Team '<Team name>' not found!", but still listed as a valid team. Tried using just the player name, teams short name, and even the longform UUID. Something seems amiss?

**Comment by Raidobw2** [comment]
That config is for fake player blocks, like Machines that do player action. Such as the builder from RFTools.
There is no such thing as adding a fake player to keep the team alive.

Normally players create their team with `/ftbteamislands create`. If you need them to be in proximity to someone or a specific team, have them join that team and clone an island with the `/clone` command, that's one option.
Second option, use a structure block to load in the island:

https://user-images.githubusercontent.com/17010632/147744725-f1523fea-fb19-45d6-8780-09f71995310b.mp4

In that one I used the default island `ftbteamislands:island` in load mode. With an offset of 1, -20, 1 according to my facing, cardinal points are on the map. The offset of -20 in Y lines it up with the sea level correctly.

This works because the islands are stored according to resource location, therefore:
![image](https://user-images.githubusercontent.com/17010632/147744902-d3a99ec2-a2ab-4fe2-93a8-55700bba6c6c.png)
You can do that with any type of island that has their nbt file in a similar format, where "structures" is the middle folder.
Or actually, any nbt structure file.

I haven't checked this repo in a while due to exams back then for school. If you have other questions that are related to a modpack or server in the future, consider asking them in the Modpack issue tracker if they are related to bugs, or if you are unsure or in any case in the FTB Discord.
I think you've seen me around there already, I really don't mind a ping if you have a question.

Side note: I haven't been able to test on server but I'm not sure if the island actually gets destroyed on leaving the team, I can't replicate the behavior on Singleplayer. The team and inventory dies, but never the island.
For the inventory problem, change that in: `config/ftbteamislands-common.toml`
![image](https://user-images.githubusercontent.com/17010632/147745515-d038e97b-581b-4af8-87fe-c0e034ce9954.png)

About the team not found message, I'll see if our modder can solve that, since player teams always exists if a certain user isn't part of a team, so that should work indeed. Still, they can change that in their menu on their own:
![image](https://user-images.githubusercontent.com/17010632/147746055-20861e85-6316-44de-a8a1-76ecd699107f.png)
![image](https://user-images.githubusercontent.com/17010632/147746072-fd8c9ccf-103d-44e3-ae6a-778a806b9a38.png)
![image](https://user-images.githubusercontent.com/17010632/147746119-279f22e1-8850-4be9-9884-9061ac8b5cbe.png)

Cheers and feel free to drop by the Discord in the future, and with a ping if you need help.
-R3GEN

**Comment by Raidobw2** [comment]
LatvianModder, here's the bug with FTB Teams probably:
![image](https://user-images.githubusercontent.com/17010632/147746567-784bd803-3aba-4255-af5a-14be1d54817e.png)

**Comment by Raidobw2** [comment]
Just tested in the latest OceanBlock with FTB Teams there, it appears to work fine after all. When I wrote that last message I had less knowledge of how the mods worked, apologies
![image](https://user-images.githubusercontent.com/17010632/183236145-f022f208-5f9c-4c79-848e-ab018e627f49.png)

For any server admins, I urge you to use a server team to set up community areas, here's how:
Creating a maintenance team `/ftbteams server create Maintenance`. Change the name to something else if you want.
Set right-clicks to be enabled `/ftbteams server settings Maintenance#45ce0d48 ftbchunks:block_interact_mode public` for example (change the \#123abc to the right thing)
Stand in the middle of the community area, say in the Overworld `/ftbchunks admin claim_as Maintenance#45ce0d48 120 ~ ~ minecraft:overworld`
This will claim as the Maintenance server team for a radius of 120 blocks. This will be around position "~ ~" which is X.Z of your player's current coordinates. "minecraft:overworld" specifies that this will claim in the Overworld, the "normal" world you spawn in.
That's it. Go through `/ftbteams server settings Maintenance#45ce0d48 [...]` to change anything about that server team.

Server teams don't contain any players, only the server itself. Only OPs or players with the correct perms with FTB Ranks can configure them.

Admins might also find `/ftbchunks admin bypass_protection` useful, because otherwise they can't modify blocks inside the community area.

I'll try and document that into some FTB Teams page in the near future for ease of use and reach for other users that may face this.
Since it looks to be working fine, I will close this as resolved
