### ISSUE TITLE
[Bug]: No Task Screen in 1.16.5

### ISSUE THREAD

**Issue by RaydanOMGr** [FTBTeam/FTB-Mods-Issues#155]
### Mod

FTB Quests

### Mod version

Idk right now, I will put this in later

### Forge / Fabric version

Forge 1.16.5 (fml version unknown right now)

### What issue are you having?

I try to submit a FE Energy quest, but there's no task screen

### Steps to reproduce

1. Start Minecraft with FTB Quests mod
2. Search task screen in inventory 
3. Don't find it

### Anything else to note?

I was using this [modpack](https://www.curseforge.com/minecraft/modpacks/thedevelopedname), searched in JEI as there is a 20K FE quest and didn't find the thing

**Comment by Raidobw2** [comment]
I will be closing this issue to track it at https://github.com/FTBTeam/FTB-Mods-Issues/issues/499, along with another similar feature that was suggested for screen tasks.
Depending on the time our mod developers have on their hands, maybe this will get backported to 1.16.5, although it is also possible this will only be reintroduced in current versions of the game (1.18, 1.19, +++).
You can subscribe to the other issue in order to receive notifications when this will be worked on
