### ISSUE TITLE
[request] ChestShop of sort?

### ISSUE THREAD

**Issue by Happiys** [FTBTeam/FTB-Mods-Issues#17]
This is only a request and could make this mod useful in the long run. Have players setup some private shops using chest like the Chest Shop plugin buy/sell items using ID codes.
Example:
[Username or FTB_Admin (for server shop)]
[ Amount ]
[ b and or s] (B = Buy) (S = Sell)
[ ID of item ]

**Comment by bookerthegeek** [comment]
### Heyo ###

Love the mod. Looking forward to when player run shops are able to be implemented. (No rush). In addition to integration with FTB money, would it be possible to add some sort of hook or API call (I am not a coder, so I apologize if those are not the correct terms) to allow plugin makers to also let their shop plugins work through claims?

Toodle-oo & Cheerio and all that jazz.

**Comment by VanillaChan6571** [comment]
@bookerthegeek 

Mean I think this mod might be abandon because clearly I forgot I was following (especially this request) this and its been 4 years and no progress or anything? So you might have to code it yourself. 😐 Only reason I re-found this post because of the recent removed assignment from my email... which tells me they couldn't figure anything to use ftb money which is sad. Maybe there is a use but I haven't played/used it since 1.12.2 so I could be wrong. Judging your statement they never made FTB Money useful.

This is why you shouldn't add modded currency and not have a shop/trading or something for the player to do. So you may need to stick with modded forge/fabric with spigot/paper.
