### ISSUE TITLE
[Bug]: Shared Quests Don't Share Rewards

### ISSUE THREAD

**Issue by MokahTGS** [FTBTeam/FTB-Mods-Issues#181]
### Mod

FTB Quests/Teams

### Mod version

FTB-quests-forge-1801.3.7-build.91

### Forge / Fabric version

Forge 39.0.44

### Modpack & version

TNP Limitless 5

### What issue are you having?

Rewards for team member are not shared even though quest completion is shared.  Only one team member can claim the rewards per team.  There is no config option to change this.

### Steps to reproduce

Join team, complete quests, only one team member gets the reward.

**Comment by Raidobw2** [comment]
Hello, can you check if this is not intentional by the modpack author? Typing `/ftbquests editing_mode true` will allow you to enter editing mode and see if the modpack author made it like that on purpose:
![image](https://user-images.githubusercontent.com/17010632/156775827-c15f0c66-da6e-48d7-a25e-9392a221dac5.png)

**Comment by MokahTGS** [comment]
Yes, I have checked that already.  It is not intentional by the modpack author.  It's just not working when it is set to true.

**Comment by Raidobw2** [comment]
Our mod devs will have to investigate then, thanks for the report and quick follow up!

**Comment by MokahTGS** [comment]
Confirmed that this does not work on 1.16.5 (Rustic Waters 2) as well.  Please fix.

**Comment by desht** [comment]
Sorry for the long delay, but I have some more info on this.

I think the problem is that the concept of "Team Reward" is the opposite of what you think it is.  Setting "Team Reward" to true means there is one reward for the team, and that's all.  TNP Limitless 5 does this (I just checked its config).

The default for "Team Reward" is false, meaning one reward per player - it can be checked by opening the GUI in editing mode, going to Settings and "Edit File". The pertinent setting is "Reward 'Team Reward'".

So this is actually correct behaviour on the part of FTB Quests, and a choice by the modpack author to only allow one reward per team.
