### ISSUE TITLE
[Bug]: FTB Chunks failed to load Correctly

### ISSUE THREAD

**Issue by Grimlock7** [FTBTeam/FTB-Mods-Issues#209]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.115

### Forge / Fabric version

1.16.5 36.2.29

### Modpack & version

Custom Pack

### What issue are you having?

Upon Pack load, i get an error stating FTB chunks hasn't loaded correctly and I'm not sure why. Same issue occurs with the previous CF build 95 as well. It may not even be specifically the mod's issue but I'd love help in figuring out the issue.

### Crashlogs

https://pste.ch/semimoruxe.rb

### Steps to reproduce

Honestly no idea, would love to know myself

### Anything else to note?

The pack also has FTB Ultimine/Library/Teams/Backups in with no issues, just an issue with chunks.

**Comment by Grimlock7** [comment]
Ok so i have information, Apparently FTB Chunks doesn't play well with the mod [MerchantMarkers](https://www.curseforge.com/minecraft/mc-mods/merchant-markers). I am unsure whether thats something FTB can fix or if its an issue with the other Mod itself.

**Comment by Raidobw2** [comment]
From looking at the error `Exception message: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetType(Lnet/minecraft/entity/Entity;)Lnet/minecraft/entity/EntityType; in merchantmarkers.mixins.json:FTBChunksClientMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap merchantmarkers.refmap.json` and their code https://github.com/AHilyard/MerchantMarkers/blob/1.18/src/main/java/com/anthonyhilyard/merchantmarkers/mixin/FTBChunksClientMixin.java I would say that they have to update their mixins probably, so this should be reported to them since they are doing integration.
I'll leave this opened so you can link it back to here if they need to speak with us or obtain any more info.

**Comment by FractalizeR** [comment]
Same issue here

**Comment by Raidobw2** [comment]
I'll be closing this since it's reported to MerchantMarkers and they will have to fix their mixin
