### ISSUE TITLE
[Feature Request]: Team members location always on rather than just player radar

### ISSUE THREAD

**Issue by KaiserThompson** [FTBTeam/FTB-Mods-Issues#245]
### Mod

FTB Chunks

### Description

I installed ftb chunks to use the chunkloading feature, dropping journeymap in the process which had been my mapping mod previously, and noticed that I couldn't see my friends on my map unless they were right next to me. Journeymap shows other player locations at all times even when they are thousands of blocks away.

### Describe the solution you'd like

Having an option toggle to allow for members of the same team to see each other on the map at any distance.

**Comment by Raidobw2** [comment]
Thanks for the suggestion

**Comment by desht** [comment]
Fixed in 1.18/1.19

Players can now be seen anywhere on map, subject to their visibility setting (`Location Visibility` in team properties).  Default is to allow allies or party members to see your location, but not everyone else.

Update rate for players outside the normal vanilla entity tracking range is much lower by default; one update per second.  This can be changed in server config (`long_range_tracker_interval`); set to 0 to disable long-range tracking entirely.  Be careful about setting this very low, especially on servers with many players; it will lead to extra network traffic.
