### ISSUE TITLE
[Bug]: Game fails to load

### ISSUE THREAD

**Issue by Zivahsdad** [FTBTeam/FTB-Mods-Issues#260]
### Mod

FTB Presents Direwolf20 1.18

### Mod version

1.0.0

### Forge / Fabric version

1.18.2-forge-40.1.19

### Modpack & version

FTB Presents Direwolf20 1.0.0

### What issue are you having?

When you load the game it flashes up quickly then you are stuck on the FTB loader and its just stays on loading.
Restarted the PC and reinstalled the pack with no luck

### Crashlogs

https://paste.feed-the-beast.com/view/38184c6e

### Steps to reproduce

1 Load FTB Launcher
2 Select FTB Presents Direwolf20 1.18 pack
3 Click Play

**Comment by Raidobw2** [comment]
Hi, the right tracker for this issue is at https://github.com/FTBTeam/FTB-Modpack-Issues/issues. I don't check this tracker very often, when I do, only for dispatching issues for our mod developers. I'm much more active on the FTB Discord and the other mentioned tracker. This results in longer wait time, like now.

This is due to a firewall configuration that's stopping the modpack to start. If you have antiviruses like Avast or AVG, turn off their firewall and you'll see if that helps. If yes, you'll need to configure them properly and checking what they blocked in order to configure them properly. If you also have a VPN, Avast or AVG may treat it as an "unsafe" network. Changing it to "trusted" will also solve that if you always have a VPN on.

This is the mods tracker so please if you have other issues following that problem, use the modpack tracker I mentioned before, or ask in the FTB Discord's support channel. I will not be replying more here, thanks for your comprehension.
