### ISSUE TITLE
[Bug]: others being able to unclaim my chunks

### ISSUE THREAD

**Issue by BETOmaqui** [FTBTeam/FTB-Mods-Issues#305]
### Mod

FTB Teams + FTB Chunks

### Mod version

ftb-teams-forge-1802.2.6-build.51 + ftb-chunks-forge-1802.3.6-build.147

### Forge / Fabric version

Forge 1.18.2 - 40.1.25

### What issue are you having?

I'm playing with my friends on a server hosted by one of us, but we found out that we're able to unclaim each other's chunks. We didn't change any settings

### Steps to reproduce

by clicking the unclaim button on someone else's chunk it is possible to unclaim

**Comment by MichaelHillcox** [comment]
Interesting, I'll look into it

**Comment by desht** [comment]
Are either or both of you op-level players? (as in, are your names in the server's `ops.json`)

Op players can freely unclaim any player's chunks, so that is the likely explanation.  I can't unclaim someone else's chunks as a regular player (just tested) on my test server, but as an op I can unclaim anything.

**Comment by MichaelHillcox** [comment]
No reply, closing
