### ISSUE TITLE
[Feature Request]: FTB Chunks - Allowed interact blocks / items config [1.18.2]

### ISSUE THREAD

**Issue by SpigotDE** [FTBTeam/FTB-Mods-Issues#347]
### Mod

FTB Chunks

### Description

On our server we wanna open the Loot Chests that the mod [Lootr](https://www.curseforge.com/minecraft/mc-mods/lootr-fabric) provides on any claimed chunk.

Is there a way i can add this at the moment?

If not could you add a line in config to add the item_id or so to interact with them ( maybe even a .json file for more ids )

Today you can open crafting tables and even anvils which brake after some use. So it should be possible

I think this config feature would bring a lot of mod and server support for players

### Describe the solution you'd like

every server owner can add the item_ids to the config or an extra .json file for "allowed interact blocks/items"

### Describe alternatives you've considered

There is no , FTB Chunks would be more better to use with other mods and you could achieve more on servers <3

**Comment by Raidobw2** [comment]
You should be able to do it with KubeJS since there are tags in place to do that. You can also do it with a normal datapack (though it requires looking stuff up).
I'll assume you have KubeJS, since it's the easiest method.

Go to `kubejs/server_scripts` and create `tags.js`. Put this inside and save the file:
```
onEvent('tags.blocks', (event) => {
  event.add('ftbchunks:interact_whitelist', 'lootr:special_loot_chest');
  event.add('ftbchunks:interact_whitelist', 'lootr:special_trapped_loot_chest');
  event.add('ftbchunks:interact_whitelist', 'lootr:special_loot_barrel');
  event.add('ftbchunks:interact_whitelist', 'lootr:special_loot_inventory');
  event.add('ftbchunks:interact_whitelist', 'lootr:special_loot_shulker');
});
```
Then type `/reload` in-game or reboot your server. I think that should do it, if not then let me know.

If that did it otherwise, feel free to close this issue unless you have other questions/concerns

**Comment by SpigotDE** [comment]
Thank you so much <3 

It works just fine with KubeJS 

I did it with all Doors as well and works too <3

May you add the events (ftbchunks:interact_whitelist , and so on) to the ftb chunks wiki. 
That way we could see all availible events 

PS:
Could you add some people in Discord, there are a lot of open questions

**Comment by Raidobw2** [comment]
Yes I will add the tags and their use to the Chunks wiki with examples, not a problem. I might add a datapack kit for server ops to simply drag and drop in their server files for quick use, which will configure some default behaviors. Not every server op wants that by default, so we can't ship it with the mod, that's why it'll be on the wiki. I will have time this upcoming week for it.

About the Discord, unsure what you mean. But if there are issues in the FTB Discord https://go.ftb.team/discord and you'd like my help with them, just ping me there, my name is "R3GEN".

If it's simply that people in the Discord ask a lot of questions about the matter in this issue, after I've added some documentation that should help these people.
