### ISSUE TITLE
[Bug]: While in editing mode, hovering over empty tiles doesn't highlight them

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#356]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1802.3.8-build.101

### Forge / Fabric version

Forge 1.18.2 40.1.60

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/178916214-795b88b6-4a08-4d2a-bba8-1f5fa0ecd136.png)
There should be a circle highlight where my cursor is

![image](https://user-images.githubusercontent.com/15698722/178918981-fc21c99b-1a70-441d-aa07-50deea21c2fc.png)
It works while moving a quest, but it should be there at all times (when in editing mode)

### Steps to reproduce

Hover over an empty tile in edit mode

**Comment by desht** [comment]
Doing this exactly as it was in 1.12 needs a custom shader to handle the 10% alpha (the highlight is still being rendered, but 10% alpha is too low for it to appear by default).

I've implemented an alternative, which is to render the default quest outline (as defined by the chapter) with an alpha of 30%. This shows up, and using the outline instead of entire shape is a lot less visually intrusive as it follows the cursor around.

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
