### ISSUE TITLE
[Bug]: Client crash when opening the map

### ISSUE THREAD

**Issue by belathus** [FTBTeam/FTB-Mods-Issues#379]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.6-build.147.jar

### Forge / Fabric version

1.18.2-40-1-51

### Modpack & version

N/A

### What issue are you having?

Mini-map stopped showing up when joining the world. When you press the key to open the large map, the client crashes. This was affecting everyone on the server.

### Crashlogs

Client Crash Log: https://gist.github.com/belathus/1a81514466358a4a04fab6a18eb060e9
Server Log: https://gist.github.com/belathus/19576d388929b5d20bd82bc0b17523ca

### Steps to reproduce

This might be difficult to reproduce. Seems to only occasionally occur on server start, and I've only seen it happen occasionally.

### Anything else to note?

Restarting the server (not the client) resolved the crash.

**Comment by MichaelHillcox** [comment]
Could you possibly email me the server setup? I think this is server specific and I'm unable to replicate it in the world / server.

My email is mikey@feed-the-beast.com

**Comment by Raidobw2** [comment]
I thought this was caused by using a vanilla server but connecting with a modded client. See https://github.com/FTBTeam/FTB-Modpack-Issues/issues/996. If you can confirm that you are using a Forge server all the time and also provide Michael with your server setup (OS, start script, mods/modpack, RAM, etc) that will help a lot!

**Comment by MichaelHillcox** [comment]
If you're connecting to a server without FTB Chunks on it, the mod will crash. I'm not sure how you're even able to join a non-modded server...

**Comment by wchristian** [comment]
I have no idea how i could answer that for you. How could i?

Also, as two further thoughts then:
- should the mod page not mention it requires server installation too? it seems a reasonable thought that even if the claiming doesn't function, the map could: https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge
- could the mod not catch the condition caused by being activated on a server with it, and at least show a reasonable message before crashing, or crash with a specific message, instead of
   `java.lang.NullPointerException: Cannot invoke "com.mojang.blaze3d.platform.Window.m_85445_()" because "this.screen" is null`

**Comment by MichaelHillcox** [comment]
Please see #616 as our main tracking issue for this crash
