### ISSUE TITLE
[Bug]: Self-deleting mods

### ISSUE THREAD

**Issue by DoctorSigma** [FTBTeam/FTB-Mods-Issues#397]
### Mod

FTB Backups

### Mod version

ftb-backups-2.1.2.2

### Forge / Fabric version

1.16.5 

### What issue are you having?

During the backup, not every time, I have almost all mods deleted from the mods folder. Only 3-6 mods remain, and your mod is not there. There are no log crashes. Nothing in latest.log and debug.log either. But it happens during backup. I can provide a profiler with a modpack where it happens.

### Steps to reproduce

1) Enter the world
2) Wait for the backup
3) After the backup, or at the end, see that the folder with mods is almost empty.

**Comment by Raidobw2** [comment]
Please provide the profiler with the modpack if you can yes, thank you

**Comment by DoctorSigma** [comment]
[1.16.5_MOD_AoI-With_Self-Deleting.zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/9276298/1.16.5_MOD_AoI-With_Self-Deleting.zip)

**Comment by Raidobw2** [comment]
Thanks, the backup configuration you're using is unusual since normally you would not backup static files like mods, config or openloader, but that shouldn't cause a problem normally I think.

What's weird is that you said you get no log info at all. The latest.log cannot be deleted while the game is running since its file is locked by the file system usually, because a file stream is opened while the game is running.

I've checked the source for the mod, there are two places where files can be deleted, and both contain logging right before deletion, so that's odd. Maybe it isn't FTB Backups but the result of something else going on?

I will check with the dev, however I'd like you to check a few things if you can:
- Did an antivirus flag the mods and delete them possibly?
- Does event viewer (Windows) / journalctl (Linux) contain anything?
- Are you developing on the CurseForge App? I believe the CurseForge App is unable to handle the same mod files in a root directory. It scans all depths of folders and keeps only one copy of the files. If you are currently backupping `mods`, this could make sense, so the backupped mods would remain but the original mods would be cleared.

Thanks in advance

**Comment by DoctorSigma** [comment]
Let's go through the questions:
1) I configured the antivirus to ALWAYS ask me before any actions on its part. That is, it is not possible for him to delete them. But then I turned off the antivirus, and nothing changed
2) I don't know much about these journals, I tried to find information about them on the Internet, since I knew they existed, but I couldn't find any. If you can tell me where it is, I'll take a look, but I haven't run minecraft for about 3-4 days, and there's hardly anything left about it.
3) I don't quite understand what you are talking about. I'm developing a modpack, that's what it is, it's also on the CurseForge website, but it's an old version, I didn't update it, because there were problems, in particular the one we're talking about. I haven't developed mods yet. If you meant something else, let me know.

I also wrote about this problem on CurseForge, they asked to download the log files of the program and minecraft, I will also attach them for you, but in the interval when this happened, I did not see anything strange in the logs, but it is not for me to judge, since I not a developer of mods. Also, in the minecraft logs, the moment when it happened is as follows:
Time: 19:21 - 19:33
Date: Or July 31 or 30. I don't remember exactly
[OverwolfLogs_2022-08-01_10-59-11 (1).zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/9276975/OverwolfLogs_2022-08-01_10-59-11.1.zip)
[Logs (1).zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/9276976/Logs.1.zip)


Well, this problem appeared during the backup. I saw this after moving the explorer to the second monitor, and watched when the mods disappeared from the folder.

Also about the configuration, that it is unusual. My CPU loads a lot during backup and the file system appears. Maybe it's because of the big world, but it hangs so much for me that even if I try to open the guide, it takes a long time to think. I tried increasing this buffer at the bottom of the config, but it doesn't seem to help much, I also set the compression level to 0, that doesn't help either, and by the way, it seems like it started removing mods after that, but I'm not sure. Although I usually have 60+ cards with 15 chunks of rendering when the local server is running, on which we play with a friend, when the backup is running, everything is dull for me, it does not freeze completely, but it lags, it's a little strange. So can you tell me if something can be changed in the config file to reduce this load, even at the expense of increasing the backup time??


I also apologize if I made a mistake somewhere. I don't know English well enough, so I write in a translator, but I try to check what he translated

**Comment by Raidobw2** [comment]
Thank you for the information. I meant if you were using the CurseForge App with Overwolf and from the logs that looks to be the case. This is the CurseForge App:

![image](https://user-images.githubusercontent.com/17010632/183315727-446c4c9f-f451-47a5-9c6e-333250fb40f1.png)

In `debug.log` I didn't see FTB Backups deleting anything but singular backup files. It also wasn't able to find the mods while doing the backup. I'm not sure what this means or if it has anything to do with the deletion.

Previous backup done (13104 files found to backup):
![image](https://user-images.githubusercontent.com/17010632/183316385-53a2ee20-61e3-453b-bee9-5574f9a92ebd.png)
![image](https://user-images.githubusercontent.com/17010632/183316154-c260cc3d-5840-480c-af58-eb449126b1da.png)

New backup being done (also tried to backup 13104 files! but couldn't find mods while doing it):
![image](https://user-images.githubusercontent.com/17010632/183316128-79fd2255-032d-4512-ba91-8c95df80fcf4.png)
![image](https://user-images.githubusercontent.com/17010632/183316089-81b07479-482a-4e6b-8be0-8cae263de568.png)
![image](https://user-images.githubusercontent.com/17010632/183316074-e87ae353-3234-4369-a284-d83037c96f48.png)
![image](https://user-images.githubusercontent.com/17010632/183315750-36821202-1170-4fc3-9edb-e47b4f69d2a7.png)

In `background.html.173.log`, the CurseForge App logs mentions that addons were uninstalled. I don't know if they were uninstalled by the CurseForge App, by FTB Backups somehow or some other 3rd party program.

```
[...]
2022-07-31 22:09:41,563 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Game instance changed: 40a52931-0827-4d76-9750-72e71b77c327 - ["Saved"]
2022-07-31 22:23:40,726 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Kotlin for Forge - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,023 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Common Capabilities - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,040 (INFO) </dist/background/background.js> (:2) - [EleriumCommunicationLayer] Fetching /categories ...
2022-07-31 22:53:33,082 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Controlling - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,085 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Cooking for Blockheads - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,184 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Cosmetic Armor Reworked - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,186 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: CraftTweaker - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,231 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Create - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,232 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Cucumber Library - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,234 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Compact Crafting - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,238 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Culinary Construct - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,243 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Curios API (Forge) - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,247 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Cyclic - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,267 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Engineer's Decor - 40a52931-0827-4d76-9750-72e71b77c327
2022-07-31 22:53:33,269 (INFO) </dist/background/background.js> (:2) - [GamesServiceImpl] Addon uninstalled detected: Cyclops Core - 40a52931-0827-4d76-9750-72e71b77c327
[...]
```

FTB Backups apparently only deletes a single file, according to the code which is open source:
https://github.com/FTBTeam/FTB-Backups/blob/573c9f8eb856e046d8a6323ae3956677f5ceea58/src/main/java/com/feed_the_beast/mods/ftbbackups/Backups.java#L296
![image](https://user-images.githubusercontent.com/17010632/183316494-d45bd18a-b7bf-4af7-8ede-e5d175e093de.png)

https://github.com/FTBTeam/FTB-Backups/blob/573c9f8eb856e046d8a6323ae3956677f5ceea58/src/main/java/com/feed_the_beast/mods/ftbbackups/Backup.java#L60
![image](https://user-images.githubusercontent.com/17010632/183316516-7e53062f-f8ab-4763-8387-67611a323ada.png)

`fileId` is what is written in the log, so `2022-07-31-22-43-17.zip` for example is a `fileId`.
The `backupsFolder` in your case is `C:\Users\DWHPC\curseforge\minecraft\Instances\1.16.5_MOD_AoI\backups`.

So that's why I'm concerned since it doesn't look possible for it to delete the `mods` folder, since it's completely outside the `backups` folder, which is the only place it can delete stuff.

There's two more things you could check for this:
- What happens if the CurseForge App and Overwolf are fully closed when Minecraft is running and performing a backup? Make sure to quit Overwolf in the masked icons completely in your taskbar.
- What if you remove `mods` from the extra files in `ftbbackups-common.toml`? Does the mod folder still deletes itself?

Thank you for your cooperation so far

**Comment by DoctorSigma** [comment]
Em. I can't reproduce the problem... I went into minecraft and had to restart the resurpacks, because of a conflict with others, I turned them all off and on one by one for another problem. When I turned on all of them, no more mods were deleted.

I don't know what it is. If I can reproduce the problem again, I will write, but maybe it was some kind of glitch??

**Comment by MichaelHillcox** [comment]
Curseforge has a known issue of deleting mods randomly, I'd say this likely falls into a Curse app issue rather than FTB backups, if you can reproduce it, please let us know and we'll reopen this issue :+1:

**Comment by Namra606** [comment]
> Curseforge has a known issue of deleting mods randomly, I'd say this likely falls into a Curse app issue rather than FTB backups, if you can reproduce it, please let us know and we'll reopen this issue 👍

Hello, i have pirated minecraft and this happened today, just now. After the game launched i noticed that there was no mods in the game and when i checked the files, all of the mods were getting deleted. No matter the circumstances, this never happened to me before.
Is there way to fix it without logs? Seems like the problem doesnt gives any errors or logs.
