### ISSUE TITLE
Veinmining doesn't require actual amount of food

### ISSUE THREAD

**Issue by VanyaBaou** [FTBTeam/FTB-Mods-Issues#443]
Veinmining is only checking for "food isn't 0" when doing an operation
This means people can have 0 food and 0 saturation and do this:
- Eat 1 beetroot, to not be starving
- Veinmine 64 blocks, hunger goes to 0
- Repeat

**Comment by desht** [comment]
Yep, the issue here is that Ultimine adds exhaustion and then checks the player's food level.  But the food level isn't updated until the next tick.  So we need to compare current exhaustion vs. current food+saturation, and stop mining if exhaustion is high enough that it would cause the player to reach food level 0.

**Comment by desht** [comment]
Fixed in 1902.4.0 release
