### ISSUE TITLE
[Bug]: FTB Ranks chat formatting does not work in 1.19.2 and in ATM8

### ISSUE THREAD

**Issue by 2lay** [FTBTeam/FTB-Mods-Issues#452]
### Mod

FTB Ranks

### Mod version

 ftb-ranks-forge-1902.1.11-build.46

### Forge / Fabric version

1.19.2 Forge 43.1.3

### What issue are you having?

Hey I have an issue that prefixes won't display on my server. I am using the same config that I used on 1.18 that worked without any problems and also prefixes doesn't work too with the default config that gets generated once the mod starts for the first time . Here's my modlist:
- architectury-6.2.43-forge
- ftb-essentials-1902.1.10-build.47
- ftb-library-forge-1902.3.9-build.144
- ftb-ranks-forge-1902.1.11-build.46

### Steps to reproduce

1. Start a fresh server with these mods
2. Give yourself the premade VIP rank
3. Prefix doesn't work

**Comment by Raidobw2** [comment]
Hello, looks like you might have to wait longer before you can use the chat formatting. This might be an early port from our mod dev, he stated the following here https://www.curseforge.com/minecraft/mc-mods/ftb-ranks-forge/files/3963619:
![image](https://user-images.githubusercontent.com/17010632/189281695-220f9b29-c6f8-4527-885d-b303ca907e80.png)

Fixing this is in his planned development schedule, so I'll close this issue since the feature isn't ported yet.
I'll also rename this issue, since there might be other people finding that problem, hopefully they'll see my message here

**Comment by Raidobw2** [comment]
P.S. There has been some changes to Minecraft's chat system with the new report stuff in 1.19.2. I'm 99% sure that's why that specific feature isn't ported yet, it probably requires code rewriting (which always takes more time than porting). Hope that helps

**Comment by sprocketaudio** [comment]
waiting for this feature too :)

**Comment by AussieWarGod** [comment]
also waiting for this feature. I'd be interested to know what broke this, as looking through the code the implementation seems relatively simple.
