### ISSUE TITLE
[Bug]: FTB Chunks 1.16.5 crash on kill

### ISSUE THREAD

**Issue by Joshernoob** [FTBTeam/FTB-Mods-Issues#455]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.115

### Forge / Fabric version

1.16.5-forge-36.2.39

### Modpack & version

Custom

### What issue are you having?

As soon as i kill any mob (thanks to crash utils) i keep crashing back to main menu with error show in crash log, so far its happened with a wandering trader and a few Lycanites Mobs mobs

### Crashlogs

https://pastebin.com/GKZEP3vN

### Steps to reproduce

1) load custom pack
2) kill any mob 
3) crash

### Anything else to note?

if needed i can give a copy of the pack for testing if it helps

**Comment by Joshernoob** [comment]
Edit: seems the morph mod as something to do with it as once removed crashes stopped

**Comment by Raidobw2** [comment]
Hmm I see, that's odd. I know of an old bug with Merchant Markers (which shows in your crash), but I think the author of that mod fixed it: https://github.com/FTBTeam/FTB-Mods-Issues/issues/209. Since you've mentioned a wandering trader and Lycanite mobs I thought that would make sense too.
Make sure you're using the latest version.

If you're sure it's the Morph mod instead, you can report to Morph. But I don't see anything in that stacktrace mentioning Morph, only FTB Chunks and Merchant Markers.

**Comment by desht** [comment]
Looking at the stacktrace, Merchant Markers is almost certainly at fault again here (I can see its mixin right before the crash).  @Joshernoob can you please test with the latest version of that mod?

**Comment by Joshernoob** [comment]
Sadly I no longer have this pack installed do to moving to 1.19 modded a few weeks ago so I can't test anything with it @desht  and since it was a custom pack would be very hard for me to re-download the exact mods it had in it

**Comment by Raidobw2** [comment]
Then I think it is safe to assume this was fixed in https://github.com/AHilyard/MerchantMarkers/issues/2, since me and Desht had the same opinion on the crash.

The full crash would have shown the version of the mods which would have been helpful, but it is truncated.

Having done custom packs before, I did not update mods often in them. I think you might have been using an older version of the mod, which would explain why you had a game crash.

I will close this issue in that case, since this appears fixed
