### ISSUE TITLE
[Feature]: Configuration option to allow Splash and lingering potions to be used in claims

### ISSUE THREAD

**Issue by DistantDig** [FTBTeam/FTB-Mods-Issues#456]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1802.3.6-build.160.jar

### Forge / Fabric version

Forge 40.1.68

### Modpack & version

RFK Reborn

### What issue are you having?

Potions seem to respect claims. Not sure if this is intended, but it is an issue for non-hostile splash or lingering potions. What leads me to believe that this is unintentional is that regular combat still works within claims, such as swords, bows, crossbows, tridents, ect. If this is intentional, perhaps remove this feature? Or allow it to be toggled off through config. 

### Steps to reproduce

1. Make a claim that you are not a part of or allied with
2. Try to throw splash potions

**Comment by Raidobw2** [comment]
There's a few tags with which you can configure this behavior for now. I'm not 100% this would work, but I could make you something quickly for you to test it.
https://github.com/FTBTeam/FTB-Chunks/tree/1.18/main/common/src/main/resources/data/ftbchunks/tags
Let me know if you have KubeJS in the modpack you're playing or not, I'll give you an adaptative test fix based on that

**Comment by desht** [comment]
@Raidobw2 is right, splash and lingering potions are currently explicitly blacklisted from use via the `ftbchunk:right_click_blacklist` tag. The issue here of course is that some of these potions are not harmful. You can allow all potion usage by removing those potion types from that tag, but that will also allow hostile players to attack you.

Next release will have a little code to explicitly allow potions with no harmful effects to be thrown.

**Comment by Raidobw2** [comment]
Nice! Thanks for that enhancement Desht!

**Comment by desht** [comment]
Fixed in 1.18/1.19
