### ISSUE TITLE
[Bug]: Death Event fires while event is canceled

### ISSUE THREAD

**Issue by Soaryn** [FTBTeam/FTB-Mods-Issues#471]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.3.9-build.163

### Forge / Fabric version

Forge 43.1.25

### What issue are you having?

If you die and a mod cancels the `LivingDeathEvent`, as per the java doc, you should not die; however, there is no check for if the event is canceled, so the death marker is always placed, which just spams the map

### Steps to reproduce

Use something that cancels the `LivingDeathEvent` something like cyclic's Totem Charm. Upon prevented death, you should notice that a marker is placed on the map.

### Anything else to note?

Be sure to check the events that are cancelable to properly use their states.

**Comment by desht** [comment]
The problem here is Architectury doesn't really provide a way to tell if incoming events are already cancelled.  However, this is probably better handled by checking for the clientside set-screen event, and checking for the vanilla `DeathScreen` - that'll only appear if the player is really dead, and we want this client-side anyway, since waypoints are clientside.

**Comment by desht** [comment]
Fixed in 1.18/1.19
