### ISSUE TITLE
[Feature Request Quests]: Port build106 to Forge 1.18.2

### ISSUE THREAD

**Issue by itsdinkd** [FTBTeam/FTB-Mods-Issues#485]
### Mod

FTB Quests

### Description

Looking at fabric's ftb quests its at build 106, and inside the changelog their is the note of the chore to bring to forge.

can this be done?

**Comment by Raidobw2** [comment]
That is planned yes. I'll poke the developer about it, though I'll close this issue since this will eventually happen in the normal development cycle of the Forge version.

**Comment by desht** [comment]
Just a quick update: there actually aren't any player-visible features in the Fabric 106 build that aren't also in the Forge 101 build, so you aren't missing out on anything.  The Forge 106 build failed to upload to Curseforge due to a temporary mod dependency issue, but that particular build didn't add any important player features.

(NB the "chore" line was actually a note of work that's been done, not a to-do entry)

In any case, the next build run will upload both Forge and Fabric builds of the mod to Curseforge at the same time.
