### ISSUE TITLE
[Feature Request]: In locked quests, the "See dependencies" button should blink red, to make it more visible

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#496]
### Mod

FTB Quests

### Description

Currently it blends a bit into the background, and a lot of players don't even know it exists.

**Comment by desht** [comment]
Good idea, and I would also make the default colour more visible when there are dependencies.  Right now it's the same as the quest border colour, which is very dark and doesn't show well.  I would suggest:

* If the quest has no dependencies, leave it dark, since it's not important
* If the quest is unlocked and has dependencies, make it lighter (same colour as the quest title makes sense here)
* If the quest is locked and has dependencies, blink the colour.  But I would avoid red since that signifies an error condition, rather than a simple "do these quests first" pointer.  Just having it blink once a second between the title and border colour (light and dark grey by default) will quickly draw the player's attention to it.

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
