### ISSUE TITLE
[Feature Request]: When opening the image search menu, before beginning the search it should have a thing saying it'll take a while and to expect a freeze

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#502]
### Mod

FTB Quests

### Description

![image](https://user-images.githubusercontent.com/15698722/196022158-251f288b-114d-4d0c-a51e-391b60949704.png)

Basically, after clicking the thing to open this but before it opens, it should have a menu saying "Loading textures, may cause lag"

**Comment by desht** [comment]
When I open this menu to add an image, I see no delay or lag.  The menu appears instantly with all the images available...

**Comment by aaronhowser1** [comment]
Try on a modpack with a couple thousand textures. It hangs for about ten
seconds in the last five packs I've developed

**Comment by desht** [comment]
Yeah, that could be slow. It might be tricky to do that - open the gui and display a message - since while it's searching for textures, the client is effectively frozen out.

What could help though:
* Cache the discovered textures and their gui buttons the first time the search window is opened (flushing the cache on a resource reload). Subsequent loads of the window should be way faster.
* Tooltip on the image button in the config screen warning that the first texture search may be slow

**Comment by aaronhowser1** [comment]
I was thinking it would go like this:

1. Click the button to open the menu
2. Instead of it opening the normal menu, it opens a menu that does nothing but display the "Loading... may lag" text, and then automatically opens the normal menu
3. The game would hang on the "Loading" menu as it loads the third menu
4. When the third menu is done loading, the game unhangs and shows the third menu as it should

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/198388760-49353c82-6be4-4af6-99e8-ab3e5a90264a.png)

Perfect fix. tyvm

**Comment by desht** [comment]
Does it seem any quicker after the first scan?

**Comment by aaronhowser1** [comment]
I hadn't noticed, but I wasn't looking. I can't remember if I even opened it a second time

**Comment by desht** [comment]
Implemented for 1.18 & 1.19
