### ISSUE TITLE
Prune Unclaimed Chunks

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Mods-Issues#55]
FTBTeam/FTB-Mods-Issues#258

**Comment by Raidobw2** [comment]
A pull request contains the changes, or handpick the code from the PR if it has too much collision, since this has been open for some time.
Our modder is a factory in itself although there's a limit to the amount of hours in a day.
Thanks for your patience, the good suggestion and the hard work put into the PR.
