### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ArcsNet** [FTBTeam/FTB-Mods-Issues#573]
### Mod

registry remapping failed

### Mod version

all of the builds for 1.19.2 above version 1.18 as of writing this cause this issue

### Forge / Fabric version

fabric 1.19.2

### What issue are you having?

![image](https://user-images.githubusercontent.com/117672284/206618389-9cf7299f-ddf3-41ee-9b85-8465ab03f3cf.png)

### Crashlogs

n/a

### Steps to reproduce

install this and ftbchunks (latest as of writing this)

**Comment by desht** [comment]
Please ensure that FTB Ranks is also installed on your client.  Latest versions of the mod must be installed on both client and server (since the `/ftbranks` command now supports tab-completion for know rank names).

**Comment by ArcsNet** [comment]
> Please ensure that FTB Ranks is also installed on your client. Latest versions of the mod must be installed on both client and server (since the `/ftbranks` command now supports tab-completion for know rank names).

is it posible to not have too do this? kinda makes the server lame if someone has too install a mod to play 🤷

**Comment by desht** [comment]
Are you trying to connect with vanilla clients (i.e. does your server currently only have server-only mods) ?

**Comment by ArcsNet** [comment]
> Are you trying to connect with vanilla clients (i.e. does your server currently only have server-only mods) ?

nah its modded its https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric

**Comment by desht** [comment]
Then... what's the problem with just adding Ranks to your client installation?

**Comment by emibanana** [comment]
> Then... what's the problem with just adding Ranks to your client installation?

there are people that been trying to install this extra mod on their mc client so they can play the server, we have provided them: 

- 300 words of instruction, 
- download link and download attachment
- 200 words pinnined message
- constant pinging to notify in game and in discord, 
- providing 1 to 1 support
- other reminder / brief instruction in every possible chat channel, 

and still, there are like 30% of ppl struggling to install it correctly after continuously trying for 2-3 days and giving up on playing.

people will ask "what do you mean instance?", "what do i find courseforge" "I dropped it in the mods folder however it still doesnt work (because they dropped it in another instance)"

**Comment by desht** [comment]
This is no longer an issue, since the latest versions of Ranks (1902.1.14 and 1802.1.11) don't require being installed on the client anymore.
