### ISSUE TITLE
[Bug]: Crash java.lang.StackOverflowError: Rendering screen

### ISSUE THREAD

**Issue by emanuele246gi** [FTBTeam/FTB-Mods-Issues#575]
### Mod

FTB Quests

### Mod version

1802.3.10-build.138

### Forge / Fabric version

1.18.2-40.1.86

### What issue are you having?

I've had this crash when I just pressed the x button in a gui and after re-joining the world the hand, throwed objects and maybe something else disappeared. it also crashes whenever I click in any chapter.

### Crashlogs

https://pste.ch/izogujosiz.pl

### Steps to reproduce

All of what I know I said it in the description.

**Comment by emanuele246gi** [comment]
Update: It crashes only on the chapter where it all started

**Comment by desht** [comment]
Somehow, you have created a circular dependency in your quests.  The Quests gui prevents adding those (detects and displays an error if you try), but has your quest book been edited directly?  This is the only way this could happen.

**Comment by emanuele246gi** [comment]
Yes I edit directly my quests, a solution that I found is by removing the quest that caused the crash from the config file and then re-creating it in the GUI

**Comment by desht** [comment]
That would explain it then.  If you do edit directly, you need to take great care not to introduce such a circular dependency.

**Comment by emanuele246gi** [comment]
That's problematic because I don't even notice when it happens, it just crashes. But anyway, I saw in another post that it's being fixed for the next version so thank you!

**Comment by desht** [comment]
Sorry, but you must have misread the other post; this issue isn't fixed elsewhere.  Editing quest files outside the GUI is unsupported behaviour.  We don't forbid it, but it's _on you_ to take care not to introduce dependency loops or otherwise break the data.  You did notice when it happens - that's what the crash was...

**Comment by emanuele246gi** [comment]
Then it should not crash, putting me in a position to fix it. Also, the mod didn't crash when I downgraded it, just by doing the same thing. 
And yes, I didn't notice it when I did it at first.

**Comment by desht** [comment]
The problem is doing this kind of validation every time the quest is checked for visibility would be terrible from a performance point of view, especially in large quest books.  Any long dependency chain would require many quests to be descended and have their quest ID's compared to ensure no loops.  This is why dependency checking is done when a new quest is created.  And it's why you need to take care if you edit quests manually.

**Comment by emanuele246gi** [comment]
Oh wait, did you mean "directly" by config files? If so then it's not, I do it from the GUI in game, sorry for the misunderstanding
