### ISSUE TITLE
[Bug]: Linked Quests should have certain properties of their own

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#612]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1902.4.4-build.146

### Forge / Fabric version

Fabric 1.19.2 0.14.11

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/210027958-cbf7f41e-ec07-4828-a87f-7d3970079bd2.png)
![image](https://user-images.githubusercontent.com/15698722/210027948-64357e92-8dad-4c1b-82ef-862349d9598c.png)
![image](https://user-images.githubusercontent.com/15698722/210027966-76844b43-b5e1-405c-9f24-2f35b54234da.png)
The X and Y properties of the linked copy show the original's, and not the copy's. 
The original quest is at (-.5,-.5) on its chapter, but its copy is at (-1.5,-4) in _its_ chapter. Editing the copy's properties edits the original's instead.

---

The size of the copy should be able to be different from the original. If the original is 2.5 large, a copy should be able to be 1 large.

### Steps to reproduce

N/A

**Comment by desht** [comment]
This is actually a little tricky, since right now quest link objects are just a thin wrapper over quest objects (with a little special handling for moving them via the GUI - but not via the edit screen, as you noticed).  Currently editing a quest link is exactly the same operation as editing the original quest object.

To make it work like you want, a bit of internal reworking would be required, the result being that editing a quest link via the "Edit" context menu entry would open a screen that *only* edits link properties (position, size, shape).  To edit the actual quest properties, it would be necessary to use the context menu on the original quest button, not any of the link(s).

If that works for you, I can look at making the necessary changes.

**Comment by aaronhowser1** [comment]
That would be fine. The Edit page could have just the things that a copy has, and maybe a link to the original's edit page

**Comment by desht** [comment]
Fixed in latest 1.18/1.19 releases
