### ISSUE TITLE
[Bug]: FTB Quests progress reset when changing FTB Ranks party

### ISSUE THREAD

**Issue by Proxwian** [FTBTeam/FTB-Mods-Issues#623]
### Mod

FTB Quests

### Mod version

 ftb-quests-forge-1802.3.12-build.157.jar

### Forge / Fabric version

1.18.2 40.2.0

### Modpack & version

OxFORTPACK x256 6.5

### What issue are you having?

On dedicated server, player has issue with invisible claimed chunks on world map from FTB Chunks, he decided to remove party and create it again, but when he leave his current party, all his quests completion progress was reset.

### Steps to reproduce

1. Have a bugged party with no claiming chunks display on worldmap
2. Leave/change current party
3. Have Quests progress reset

**Comment by desht** [comment]
It's expected behaviour that quest progress is lost when leaving a party - progress is specifically tied to your team ID, not your player ID.  (A special case is for a player who isn't in a team, when their "team" ID is the same as the player ID).  Was the player the only player in the party team when they left the team?

What's of more interest is why this player has invisible claimed chunks, but I would need a lot more information about how this occurred to be able to offer any advice there.

**Comment by Proxwian** [comment]
That's the point, right, I didn'e expected that quest progress tied to party, not to the player. Also I didn't found any configuration about that, is it exist?

**Comment by desht** [comment]
No, quest progress is *always* tied to the team, never to the individual player.

**Comment by Proxwian** [comment]
No, there's a couple

**Comment by desht** [comment]
Then the player most certainly should NOT keep their progress.  Otherwise that would allow abuse of the system (join a party, do nothing for a few weeks, leave the party, have all the progress without playing).

There is an argument for allowing quest progress to be transferred back to the owner of a party if they are last to leave and disband the party, but even that needs careful consideration.
