### ISSUE TITLE
[Feature Request]: Waypoint (dot) fade distance

### ISSUE THREAD

**Issue by Looodon** [FTBTeam/FTB-Mods-Issues#669]
### Mod

FTBChunks

### Mod version

ftb-chunks-forge-1902.3.15-build.233

### Forge / Fabric version

Forge 43.2.3

### What issue are you having?

hey, i set up the "waypoint fade distance" to 3 yet no matter how far i move away i still see the "x" of the way point in-game. I thought there was a way for waypoints (the X) to disappear in-game when you're far away. I dont know if i remember wrong 

### Steps to reproduce

1. set waypoint fade distance
2. move away from the waypoint

**Comment by desht** [comment]
For the dots, they don't fade, no.  But you can hide them via the waypoint manager.

I guess it might be nice to have those fade in the same way beacons do?  But there's also an argument to keep them there, e.g. you might be trying to find a waypoint behind a wall, and you don't want it disappearing when you're close.  The beacon is more visually obtrusive than the waypoint dot, which is why it fades out when you get close enough to it.

**Comment by desht** [comment]
This could be done with a new client-side config setting - "Waypoint Dot Fade Distance".  And probably rename the existing "Waypoint fade distance" to "Waypoint Beacon Fade Distance".

**Comment by desht** [comment]
Fixed in latest Chunks release

**Comment by desht** [comment]
It being set to 1 by default is intentional.  It means the default behaviour is same as before, not to cause any surprises to people who are used to that.

I do not see that "833m away" behaviour you describe at all. E.g. setting to 12 means it starts fading out when you're 12 blocks away, as expected.
