### ISSUE TITLE
Add a list where the players can see all their waypoints, rename, delete and hide/unhide them. 

### ISSUE THREAD

**Issue by gtm-nayan** [FTBTeam/FTB-Mods-Issues#67]
Within the world map GUI, there should be a way to access a list of all waypoints set by the user which allows performing the actions mentioned above.

**Comment by credomane** [comment]
Just to add. I'd love to be able to add (and edit) waypoint by their exact coords. That is the *only* reason I still use a different mod for waypoints. Making a waypoint can be annoying when the mod decides (incorrectly) that Y-64 is where the marker will be or you later find out you were a couple blocks off originally and just want to move the current WP instead of having to remake it.

**Comment by desht** [comment]
That's probably something that could be worked into the new manager GUI, yes.

Also, the next release will allow waypoints to be added (via hotkey) exactly where the player is standing.
