### ISSUE TITLE
[Bug]: ic2c mining laser destroys blocks in protected zones, but only with explosion mode

### ISSUE THREAD

**Issue by Shizz00** [FTBTeam/FTB-Mods-Issues#672]
### Mod

FTB chunks

### Mod version

ftb-chunks-forge-1902.3.14-build.218.jar

### Forge / Fabric version

forge-1.19.2-43.2.0-installer.jar

### What issue are you having?

I don't know if the issue is this mod or ic2c, but the laser itself works... Sooo it's just a protection thing i guess?
Anyway, all other modes of the ic2c mining laser won't destroy blocks in protected zones. It's just the explosion mode, that is stronger than a tnt block, which destroys blocks.

### Steps to reproduce

1. set ic2c mining laser to "expolsive"
2. go to another protected zone where you have no access
3. shoot laser, blocks explode

**Comment by desht** [comment]
FTB Chunks protects blocks for any well-behaved mod, i.e. which fires block break and explosion events.  It cannot protect against mods which just destroy blocks.  IC2 Classic is a closed-source mod, meaning I cannot examine it to determine how its explosions work.  Therefore I would suggest you take it up with the author of that mod.

**Comment by Speiger** [comment]
@desht IC2C supports the Start event of the Explosion event and not the modification of it.
The reason is that forge doesn't support custom explosions sadly. It has to be a vanilla explosion, which is a fixed implementation.

I can hopefully next solve this with dealing 2 explosion events and make it work that way but otherwise it would force me to either spam them for every single entity/block affected or come up with some crazy shit.

2 explosions because of this:
-1: For all the entities affected so you can filter them before this kicks in.
-2: For all blocks that were affected AFTER all Entities were damaged.

This is the best i can think of.

Also:
>  IC2 Classic is a closed-source mod, meaning I cannot examine it to determine how its explosions work

Unless you refer to FastCraft or Optifine this argument is bullshit.
Yes a closed source mod/arr are closed source but the nature of java code is open source to begin with.
So unless obfuscation is used this argument is bullshit.

**Comment by desht** [comment]
> but the nature of java code is open source to begin with

Can you point me to the source of IC2C then, please?  Your github repo only appears to include the API.

**Comment by desht** [comment]
BTW, custom explosions are totally possible to do with Forge.  Immersive Engineering does it, for example; it calls `ForgeEventFactory.onExplosionDetonate()` from its custom explosion code to fire the `ExplosionEvent.Detonate` event at the right time.

**Comment by Speiger** [comment]
> > but the nature of java code is open source to begin with
> 
> Can you point me to the source of IC2C then, please? Your github repo only appears to include the API.

[This is where i got your sourcecode from](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/files/4373742)


> BTW, custom explosions are totally possible to do with Forge. Immersive Engineering does it, for example; it calls `ForgeEventFactory.onExplosionDetonate()` from its custom explosion code to fire the `ExplosionEvent.Detonate` event at the right time.

Doesn't help when i have a empty block list when entities get damaged and when the blockList for me is a Map and the Class i am using is IC2Explosion that uses a "Explosion" as fake to be mod compatible.

In other words I have to make wrappers/synchronization tools for everything to make it work.
And this heavily optimized explosion (because mcs explosion can't handle nukes) isn't really compatible with forge event if "Explosion" is either a fake or null.

So What i have to do:
1: Collect all entities
2: Run the first event with a empty block list and the collected entities and make sure entities match.
3: Do the entity part and the collection part of the explosion.
4: create another fake explosion/recycle the previous one and insert all the blockPos, which fun fact i have to create since i use a Long2Long map to store the Positions that have to be deleted to optimize for a lot of things. And Whoops we have a performance drain.
5: find a good way to do it without breaking the resulting performance.

So if it isn't fixable by me due to lag issues then oh well Nukes/Mining lasers do have special privileges.

**Comment by desht** [comment]
> This is where i got your sourcecode from

Not sure how that's relevant, since I asked you where the source of IC2C is.  I was trying to determine why you don't fire explosion events properly which would require me inspecting your source code.  But you clearly aren't interested in cooperating, so we're done here.

For the record, FTB Chunks is visible source (although not open source), and you could have easily followed the "Source" link from the Curseforge project to find that. Sorry if that was too difficult.

**Comment by Speiger** [comment]
@desht if decompilation says nothing to you then i can't help you.

And i am legally obligated to have it closed source so i am sorry, not possible.

**Comment by Speiger** [comment]
@desht addressed in the next patch.
Small caviate: The Check is thrown 2x first one with just entities and one with just Blocks.
So its at least detectable xD

Also for next time you find a "CLOSED SOURCE DANGEROUSE MOD" simply download it via curse maven and you get source code access with Intellij since they come with a decompiler and the cursemaven + fg.decomiple simply allow you to view the source.

**Comment by desht** [comment]
Yeah, I know to deobfuscate mods, thanks for the lesson /s

I just don't want to be wasting time doing that with closed source mods.  You publish closed source, that's fine, but you get to answer the questions, not me.

**Comment by Speiger** [comment]
> I just don't want to be wasting time doing that with closed source mods. You publish closed source, that's fine, but you get to answer the questions, not me.

> IC2 Classic is a closed-source mod, meaning I cannot examine it to determine how its explosions work.

Between: "I don't want to" and "I can't" are two different stories.
Its fine if you don't want to do that, but then SAY IT.

But good to know how you can steal FTB mods. Simply make the version closed source and they will never be able to tell if it was stolen or not. /s

Jokes aside, this just leaves a bad taste in my mouth in terms of wanting to be compatible with FTB Mods.
No you are not on my "Shitlist" for this, but next time instead of outright saying: I won't check it so it won't be addressed, simply ping me in github and ask me for details, instead of having the user to find me and then make it possible to be addressed, that makes it easier for everyone involved.

Anyways, the issue is addressed from my side, just don't trust the explosion type xD
