### ISSUE TITLE
[Feature Request]: Animated quest images

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#690]
### Mod

FTB Quests

### Description

Being able to use textures animated via .mcmeta would be very nice

**Comment by desht** [comment]
Actually needs an FTB Library change, in the quest selection screen. Currently the screen just scans for all known textures in the resource manager; it will need changing to check if these textures are loaded in the block atlas, and so available as `TextureAtlasSprite` instead of simple textures (which will then automatically support animated textures via the mcmeta system).

**Comment by desht** [comment]
Fixed in latest FTB Library release
