### ISSUE TITLE
[Bug]: Cannot use & formatting when using tellraw format

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#696]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.8-build.190

### Forge / Fabric version

1.19.2 43.2.4

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/220556736-be50680a-5fc0-4909-8092-d2bfc8255713.png)

["",{"translate":"university.stress.desc2.1"},{"translate":"university.stress.desc2.2","color":"light_purple","clickEvent":{"action":"change_page","value":"5E076059A0164590"},"hoverEvent":{"action":"show_text","contents":[{"translate":"university.stress.desc2.2text"}]}}]

```json
    "university.stress.desc1":"Rotational force is made up of two things: Speed, and Stress.",
    "university.stress.desc2.1":"&bSpeed&r is how fast the part is moving. Most machines work better when they run faster. Speed can be measured in the ",
    "university.stress.desc2.2":"Speedometer.",
```

### Steps to reproduce

na

**Comment by desht** [comment]
I'm not sure this is directly fixable, since Components built this way are all handled internal to vanilla's component deserialization system. FTB Quests/Library doesn't really get a chance to intervene in this process to replace characters.

It might be possible to kludge this by using the literal Unicode section symbol (§), which is how literal markup codes are actually represented in Minecraft, instead of the ampersand (which has always been an unofficial hack anyway since it's easier to type than the section symbol).

```json
"university.stress.desc1":"Rotational force is made up of two things: Speed, and Stress.",
"university.stress.desc2.1":"§bSpeed§r is how fast the part is moving. Most machines work better when they run faster. Speed can be measured in the ",
"university.stress.desc2.2":"Speedometer.",
```

**Comment by desht** [comment]
Just checking you saw my reply to this - did you get a chance to test using the § notation?

**Comment by aaronhowser1** [comment]
Oh no, i'll try it now

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/223715551-6b15251e-1d52-49fe-9988-9daf196087dd.png)
![image](https://user-images.githubusercontent.com/15698722/223715567-95d1ea0c-0a6d-4b5f-ac5b-092e271af367.png)
That does work!

**Comment by desht** [comment]
Cool, closing this.  I think this is the best way of handling it.
