### ISSUE TITLE
[Bug]: Certain items have the name repeated in tasks

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#733]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.10-build.200

### Forge / Fabric version

Forge 43.2.6

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/228818130-936df6fa-48d5-4ac8-8f42-13709ec69b92.png)

![image](https://user-images.githubusercontent.com/15698722/228818159-4ab2fde6-06b2-456c-84c2-5808376d52c9.png)

This task has no special anything, like custom name etc. It's a freshly made task that's just had the item set and nothing else changed.

This is the first item I've seen do this. All of Thermal Series' Integral Components do this, and nothing else that I've noticed.

### Steps to reproduce

Make a task using Integral Components from Thermal.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/228818977-f7074b58-6c07-4614-8af8-eb944eb54491.png)
![image](https://user-images.githubusercontent.com/15698722/228819009-d565eb19-d3c8-4803-a111-2168b8436142.png)
Actually, so are Thermal's machines. Very very strange.

![image](https://user-images.githubusercontent.com/15698722/228819139-09887ff8-47a3-433f-abae-829d766e34a0.png)
It's not ALL Thermal items though, which is very interesting.

**Comment by desht** [comment]
Yeah, I can see why it's happening... there's a fair bit of hackiness in the tooltip code for item tasks there trying to determine whether or not to include the whole tooltip or lose the first line (because it's already been added, as the item name).  Normally the first line is dropped but in this case the Thermal items have a bit of hidden text in the text component which doesn't display, but is enough to fool Quests into thinking it's not the actual item name.

I'll find a (hopefully clean) way to work around this.

**Comment by desht** [comment]
Fixed in 1902.4.13
