### ISSUE TITLE
[Bug]: FTB Library breaks display name formatting in other mods

### ISSUE THREAD

**Issue by jenchanws** [FTBTeam/FTB-Mods-Issues#748]
### Mod

FTB Library

### Mod version

 ftb-library-fabric:1902.3.16-build.193

### Forge / Fabric version

Fabric Loader 0.14.17 / Minecraft 1.19.2

### What issue are you having?

Mods such as [Styled Chat](https://github.com/Patbox/StyledChat) that manipulate player display names are no longer changing them as expected; instead, only the vanilla display name is showing.

I've managed to track it down to the addition of the [`PlayerMixin`](https://github.com/FTBTeam/FTB-Library/blob/1.19/main/fabric/src/main/java/dev/ftb/mods/ftblibrary/core/mixin/fabric/PlayerMixin.java) in [`d87a9de`](https://github.com/FTBTeam/FTB-Library/commit/d87a9de0270fabf2602de8c57b864a4625755368). Using the previous release (1902.3.15-build.188) reverts to the correct behavior.

### Steps to reproduce

1. Install Styled Chat 2.0.2 and FTB Library 1902.3.16-build.193 on a Fabric 1.19.2 server (on my server, FTB Library was used as a dependency for Ultimine)
2. Modify the Styled Chat config (`config/styled-chat.json`) to include any kind of formatting besides the username:

    ```js
    "default": {
      "display_name": "<blue>${name}</blue>",
      // ...
    },
    ```

3. Run `/styledchat reload` to reload the config
4. Note that chat messages do not include formatting on the display name:
    
    <img width="134" alt="Screenshot 2023-04-07 at 2 55 58 AM" src="https://user-images.githubusercontent.com/65937586/230578819-7c717fb9-f9ae-4eb9-b8c5-ce7122366ad1.png">

    The expected behavior is for the name to be blue, as specified in the config.

**Comment by Patbox** [comment]
More and more people are reporting this issue when using Styled Chat/Nicknames mods. I hope it could be solved soon. as agresive caching and always forced display name override just break my mods

**Comment by desht** [comment]
Yep, it does cache too agressively right now.  I will take a look at the problem.

**Comment by desht** [comment]
This should now be fixed in the latest dev build for FTB Library.  A quick explanation:

FTB Library adds a local custom Fabric API event (`PlayerDisplayNameCallback`) which the above-mentioned player mixin fires. This allows two of our other mods (FTB Ranks and FTB Essentials) to modify the player's display name without stepping on each other's toes.  It works rather like the Forge `PlayerEvent.NameFormat` event in that regard, but Fabric doesn't currently have an equivalent.

But it was indeed caching the player name when no listeners were registered, which would be the case if Ranks and/or Essentials were not in use.  So I've modified it to do no caching in this case.

Note that if Ranks or Essentials are present and do make any changes, player names will still be cached.  Caching is important for performance, since `Player#getDisplayName` gets called a lot.  But ultimately, if there are multiple mods making changes to the player's display name, a certain amount of conflict is likely.

Ideally this event should be in FAPI, and I do plan to try and get it included.  It would be useful to have any name-changing mods use this, and where possible combine changes in an orderly fashion (the event gets the modified name from the previous handler, so mods which just want to append something, for example, can play nicely).

The next release of FTB Library will contain this change, but you'd like to test it now, you can get the dev build at https://maven-admin.ftb.dev/repository/maven-public/dev/ftb/mods/ftb-library-fabric/1902.3.18-build.204/ftb-library-fabric-1902.3.18-build.204.jar
