### ISSUE TITLE
[Feature Request]: Hide Specific Dependency Lines

### ISSUE THREAD

**Issue by FooterMan15** [FTBTeam/FTB-Mods-Issues#754]
### Mod

FTBQuests

### Description

Add a way to only hide specific dependency lines from Quests with multiple dependencies.

### Describe the solution you'd like

In the Dependencies tab in a Quest's edit menu, put an option onto the Dependency entries that can hide the line created.

**Comment by desht** [comment]
I'm not sure I understand the use-case for this.  Can you explain please why this would be a useful feature?

**Comment by FooterMan15** [comment]
So, I have some Ingots in the top left:
![image](https://user-images.githubusercontent.com/71946346/232787595-3413a2a8-8d36-4226-a08d-0351577f19a6.png)
I could block Quests until those materials have been obtained, but I don't want lines going to the recipes unlocked by them, because that would be a little ridiculous.
![image](https://user-images.githubusercontent.com/71946346/232788506-13d422c3-394f-4445-802c-e3667b353053.png)
For example, the MV Wiring. It takes Electrum as a dependency. If I wanted to hide that line, I'd have to turn off all lines from that Quest's dependencies, which then looks like LV Wiring can be skipped, when it can't.

Hopefully it's not confusing.

**Comment by desht** [comment]
Sorry, this one fell by the wayside a bit.  Rather than a way to choose specific dependency lines to hide (which would be awkward both to code and to use), I think a better way to handle this would be a new boolean property "Hide Dependent Lines".  With that, you'd be able to select the three ingot quest in the top left & set "Hide Dependent Lines" to true, and those long dependency lines would become invisible.

Thoughts?

**Comment by FooterMan15** [comment]
Sounds good to me, I understand the troubles with the code.

**Comment by desht** [comment]
Added in latest release.
