### ISSUE TITLE
FTB Ultimine mines out deepslate along with andesite even when pickaxe isn't high enough tier

### ISSUE THREAD

**Issue by Xetaxheb** [FTBTeam/FTB-Mods-Issues#776]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

If you ultimine some andesite with a stone tinkers pickaxe it also breaks the deepslate

### Steps to reproduce

1. Make tinkers stone pickaxe
2. Ultimine andesite near andesite-deepslate border

### Expected behaviour

Not to break different blocks

**Comment by desht** [comment]
Sorry for the delay on this.

Are Tinker's stone pickaxes really not able to mine deepslate?  Deepslate is mineable with a vanilla wooden pickaxe so it doesn't make a lot of sense that a stone Tinker's pickaxe would not be able to mine it.  If that's the case, I'd suggest it's a problem with Tinker's, not with FTB Ultimine.

Default FTB Ultimine settings consider deepslate equivalent to andesite when doing shapeless mining, because both blocks are the `minecraft:base_stone_overworld` block tag.  So I don't see a problem with FTB Ultimine here.

**Comment by desht** [comment]
> It shouldn't be checking mineability based on blocktags, surely?

Why not? That's how it works.  And the tags it uses are configurable.

However, the mod does also check destroy speed of additional blocks, and will skip over blocks with a long break time than the block mined.

Deepslate does take twice as long to break as Andesite, and in my testing just now, ultimining an Andesite block with a Deepslate block right beside broke the Andesite, but not the Deepslate.  Which is correct behaviour.

**Comment by desht** [comment]
Update: Just realized, you're on 1.18.  The fixed behaviour is in 1.19/1.20 - looking at the 1.18 code for Ultimine, Deepslate would indeed get broken.

**Comment by desht** [comment]
Sorry, not following you at all.  Deepslate has a harvest level of wooden tool.  You can mine deepslate with a wooden pickaxe; harvest level is entirely irrelevant here.  So there's absolutely no reason it shouldn't be mined along with andesite; apart from anything else, vanilla considers a base stone block (hence the `minecraft:base_stone_overworld` tag).

**Comment by desht** [comment]
OK yeah, I see Stoneblock specifically changes the harvest level to require a diamond pick.  That's not something Ultimine accounts for right now.

I can take a look at that.
