### ISSUE TITLE
[Bug]: FTB Quests

### ISSUE THREAD

**Issue by toastonrye** [FTBTeam/FTB-Mods-Issues#777]
### Mod

FTB Quests

### Mod version

1605.3.7-build.165

### Forge / Fabric version

1.16.5-36.2.39

### Modpack & version

Stacia 1.22.1

### What issue are you having?

On a server, I've somehow broken the quest book. A quest wasn't being detected because of tags, so I edited the quest to accept the proper type of material. And it completed and I turned off editing mode.

The  next morning when I log in, I can't open the quest book, the mod is still installed but it says,

"Error?! Server doesn't have" and the message gets cut off, because the notification with the important part of the information doesn't fit....

### Steps to reproduce

It's described above, I went into editing mode, added a missing tag to detect completion, it worked and I turned off editing mode. The next morning I wasn't able to use quests anymore.

**Comment by toastonrye** [comment]
After several minutes of afk'ing on the server it works. maybe something was still loading after join? It still would be nice to know what the full error message said.

**Comment by desht** [comment]
Just for reference, the full error is "Error?! Server doesn't have FTB Quests!", which is usually the result of the client not receiving any questbook data from the server, which could be the case if the server-side data was corrupt or otherwise couldn't be loaded.

Sounds like your problem resolved itself, though, so hopefully all is well now.
