### ISSUE TITLE
[Bug]: 1.19.2 Repeatable quest + 2 rewards or auto-claim = endless bugs

### ISSUE THREAD

**Issue by BlackAures1** [FTBTeam/FTB-Mods-Issues#807]
### Mod

Quest

### Mod version

ftb-quests-forge-1902.4.15-build.228

### Forge / Fabric version

1.19.2 43.2.11

### Modpack & version

Play as dragon Gothic Edition

### What issue are you having?

1. If there are more than two rewards in a repeatable quest, you cannot get the second reward if you get one of them (it is not clickable and cannot be cancelled). Example: 1 reward is obtained, but the second reward is broken and I can no longer repeat the quest. Resetting all progress doesn't help fix the problem. With one reward everything works correctly.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/4c5df50b-fa4c-4ea1-9eca-a3f327045561)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/54b88dde-79bd-4605-9889-12e73e710369)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/2b5adc4a-89f6-408f-b6c6-e1936235b24d)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/b797f3b3-37f7-4701-a192-cffce17de930)

-------

2. If an reward has "auto-claim = true", then I get about 10-20 rolls of this loot, but not one roll as without "receive automatically".

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/4148e51f-58b9-4d65-bca9-977eb4cfd5da)

### Crashlogs

[latest.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/11525989/latest.log)

### Steps to reproduce

First Bug:
1. Create any repeatable quest with an item (submit).
2. Make one reward as a "random reward" and the other as an "item".
3. Try to complete the quest and collect the reward.
4. One reward will be bogged down and impossible to pick up.

Second Bug:
To get the second bug, create absolutely any repeatable quest and add "auto-claim" to the reward, try to complete the quest and enjoy

### Anything else to note?

The new interface update is good, but you should not have added an additional button in the "Quick Edit Properties" menu. Waste of time for one more click.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/6196369f-1f2e-42e3-9307-21f54faae414)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/43911230/77aa9fba-9a48-416e-9ec5-31a99fa74129)

**Comment by desht** [comment]
Looks like both bugs are basically a server->client desync due to sending an extra claim confirmation response to the client. Think I have a fix, need to do a bit more testing though.

> The new interface update is good, but you should not have added an additional button in the "Quick Edit Properties" menu. Waste of time for one more click.

Not quite sure what you mean by this. It was added because some people find it useful. If you don't find it useful, then just don't use it?

**Comment by BlackAures1** [comment]
> Looks like both bugs are basically a server->client desync due to sending an extra claim confirmation response to the client. Think I have a fix, need to do a bit more testing though.
I tested it yesterday only in single player, but I understand that even in singles there is a delay between the moment when the player does something and the game will count the result. Thanks for the quick fix, that's very cool!

> Not quite sure what you mean by this. It was added because some people find it useful. If you don't find it useful, then just don't use it?
Yes, you really misunderstood me. I'm sorry if I was too brief in my indignation. I meant that in the past I didn't need to make an extra click to get these quick features, but then FTB decided to hide them in addition menu. On the contrary, I want to use this menu, but without having to make an extra click. Right now there are very few mass editing functions available and each quest has to be edited individually. It takes a lot of time as it is. I couldn't find any information on the website about the hotkeys for the items in this menu.

**Comment by desht** [comment]
>  I meant that in the past I didn't need to make an extra click to get these quick features

Actually, the "Quick Edit Properties..." is a new addition that makes it easier to adjust those properties which can be adjusted with a simple click. Before that was added,it was necessary to click "Edit" to open the full properties screen, adjust the property, and then accept the changes.  This extra menu item allows several properties to be edited more conveniently. Those properties have never been a part of the top-level context menu.

You're right about the lack of mass editing functions though and it's something I do want to improve. Unfortunately due to the current coding, it's harder than I hoped (I've already started looking at a clean way to get this working).
