### ISSUE TITLE
[Bug]: Reset world on server, client can no longer connect.

### ISSUE THREAD

**Issue by ButterMe8aby** [FTBTeam/FTB-Mods-Issues#839]
### Mod

FTB Chunks (Fabric)

### Mod version

ftb-chunks-fabric-1802.3.15-build.243

### Forge / Fabric version

0.14.12

### What issue are you having?

Reset the world on my server but now every client gets the same issue when trying to connect. Shows joining world, then saving world, and then Minecraft crashes. I'm very new to this so I'm sure I'm just being dumb.

### Crashlogs

[crash-2023-06-15_13.15.52-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/11760895/crash-2023-06-15_13.15.52-client.txt)

### Steps to reproduce

1. Make world and claim chunks.
2. Reset world or generate a new one on the server.
3. Rejoin to get crashed on client side.

### Anything else to note?

I'm pretty sure it's just FTB Chunks trying to load in chunks that were claimed/force-loaded that don't exist anymore. I'm just not bright enough to do anything about it if that is the issue.

**Comment by desht** [comment]
This isn't a bug in FTB Chunks, but a problem in how the SeasonHUD mod is calling into FTB Chunks.  The mod is doing it wrongly, and I'm amazed this ever worked.

Specifically, the call to `FTBChunksAPI.getManager()` crashes because the team manager here is a server-side object which simply does not exist on the client.

The data that SeasonHUD needs can be obtained through the `MapDimension` object they have (which is valid on the client), using code like this:

```java
MapDimension dim = MapDimension.getCurrent();
BlockPos playerPos = player.blockPosition();
MapChunk mapChunk = dim.getRegion(XZ.regionFromBlock(playerPos))
    .getData()
    .getChunk(XZ.chunkFromBlock(playerPos));
ClientTeam team = MapChunk.getTeam();
```

`team` will be non-null if the chunk is claimed by a team.

I would suggest raising an issue with the SereneHUD mod, quoting the above as a fix.  The author is welcome to contact me for more information if necessary.
