### ISSUE TITLE
[Bug]: Opening the Quest Book centers your mouse on the screen

### ISSUE THREAD

**Issue by SeooY** [FTBTeam/FTB-Mods-Issues#847]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1902.4.17-build.240

### Forge / Fabric version

1.19.2 43.2.13

### Modpack & version

Enigmatica 9 in-dev

### What issue are you having?

Opening the Quest Book centers your mouse on the screen. I tested it in a previous version (ftb-quests-forge-1902.4.16-build.235) and it worked as expected, respecting the mouse position, but with the newer version it always centers the mouse on the screen, which is disruptive.

### Steps to reproduce

1. Open the Quest Book with your mouse anywhere but not in the center.
2. Notice that the mouse is centered on the screen after opening the Quest Book.

**Comment by desht** [comment]
Not sure I understand.  When I open the FTB Quest GUI, the mouse is centered, yes... but that's the case with _any_ GUI.  Open your inventory with E, right click a chest... the mouse pointer is centered.

So I guess I'm missing something here..?

**Comment by SeooY** [comment]
That wasn't the case in a previous version. In those examples (opening your inventory with E, right clicking a chest), having the mouse pointer in the center is normal because that's where your crosshair is, and there isn't any additional GUI where you can move the mouse before you access those.

In FTB Quest's case, a lot of people open it from the button at the top left corner of the screen when you open your inventory. Previously, it respected the position of the mouse at that moment, and when it opened the Quest GUI, it left the mouse at the top left corner where you just clicked the icon. Now, it moves it to the center of the screen, which is disruptive to the user experience.

Another good example is FTB Chunks: it's working correctly there. There's also an icon in the top left corner, and when you click it, it opens the Maps/Claims GUI but leaving the mouse exactly where it was a screen ago, it doesn't reset it.

**Comment by desht** [comment]
Ah, using the sidebar button. Sorry, that wasn't clear.

Yeah, the behaviour has changed, due to this issue: https://github.com/FTBTeam/FTB-Mods-Issues/issues/828

Basically the client could get stuck in an infinite loop between Quests and REI, since both mods have a "go to the previous screen" feature, which could generally only be escaped by killing the client - not ideal.  So I forced a screen close before opening Quests when the sidebar button is pressed, to break that loop.  Unfortunately closing the screen means Minecraft grabs the pointer again and re-centers it, so it jumps when Quests opens.

I agree that's a poor UX, and I'll see if there's a possible way around this. Ultimately though, a jumping pointer is better than a locked-up client...

**Comment by desht** [comment]
Fixed in 1902.4.18
