### ISSUE TITLE
[Bug]: Server Crash WarmupCooldownTeleporter

### ISSUE THREAD

**Issue by aws0jam** [FTBTeam/FTB-Mods-Issues#865]
### Mod

FTB Essentials

### Mod version

ftb-chunks-forge-1902.3.22

### Forge / Fabric version

forge-1.19.2-43.2.14-

### What issue are you having?

I don't know for sure, but I think that something happens during teleportation and the server crashes

### Crashlogs

https://pste.ch/ibidenaquf.rb

### Steps to reproduce

Perhaps the players teleport from twilight to the overworld

**Comment by desht** [comment]
`ftb-essentials-forge-1902.3.3-build.9999.jar`

Why are you running a dev build here?

**Comment by aws0jam** [comment]
Because of luckperm support.

**Comment by desht** [comment]
FTB Essentials 1902.3.3 as published on CurseForge includes luckperms support, so please use that.

While you're welcome to build and use dev builds, please do not raise issues against them. If you're building and running your own dev build, you're expected to be able to debug issues yourself.

**Comment by aws0jam** [comment]
https://pste.ch/sucoqucuxe.coffeescript get same arror with non dev build

**Comment by desht** [comment]
This one might be hard to track down, since I can't reproduce it, and I can't see what in the code would cause a CME.  CME's can generally open happen if there's multithreaded access going on (there isn't here), or if something modifies the hashmap during iteration (again, not happening).

I've made an experimental change which isolate all modifications to the hashmap to the tick method, which you can try out - get it from https://maven.saps.dev/releases/dev/ftb/mods/ftb-essentials-forge/1902.3.4-build.101/ftb-essentials-forge-1902.3.4-build.101.jar

Can't guarantee it'll help, but even if not it might provide some more clues as to what's happening.

**Comment by desht** [comment]
Just checking if you've had a chance to try that dev build?

**Comment by oozeyyy** [comment]
I can reproduce this on my TNP LL7 server consistently, on v18 it crashes whenever a player teleports from another dimension (nether) into another (overworld) with warmup enabled.

Mod ver - ftb-essentials-forge-2001.1.2.jar
MC ver - 1.20.1
Forge - 47.1.3

Crashlog - 

[crash-2023-08-20_18.55.20-server.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/12389268/crash-2023-08-20_18.55.20-server.txt)

**Comment by desht** [comment]
@oozeyyy have _you_ tried that dev build?
