### ISSUE TITLE
[Bug]:  FTB Chunks clientside memory usage (Linux)

### ISSUE THREAD

**Issue by costelush41** [FTBTeam/FTB-Mods-Issues#937]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1902.4.2-build.302

### Forge / Fabric version

Forge 43.2.14

### Modpack & version

All The Mods 8

### What issue are you having?

[22:31:02] [Render thread/INFO] [FTB Chunks/]: Shutting down map thread

FTB Chunks will not release my ram, it will add up to my maximum ram even though I have allocated from 8 to 10 GB. Max I have 32GB.

### Steps to reproduce

From my end I thought it was a memory leak.
Playing on a local server, server runs fine but the client is affected.
Tried on a single player world too, played for 5 seconds and closed the game, java still hogs my memory and the last message in the logs is the one that i mentioned.
Running on Linux 22.04, same issue on 23.04.
Tried Java 17.0.4,  17.0.8 and 17.0.8.1
Tried multiple launchers available on Linux and some behave really strange like they do not want to detect the proper Java version installed.
Made sure I used the right args.

I dont think this issue is happening on Windows.
I prefer to use Linux over Windows as Linux has better resource management and the FPS boost is out
I've been dealing with this issue for so long and I am extremely tired and fed up.

Thanks in advance

**Comment by desht** [comment]
First off, it's important to note that Linux and Windows use completely different memory management systems, and used memory as reported by Linux is not necessarily physically allocated (in particular memory the JVM allocates and then released is not necessarily reported as released by the OS until it needs that memory for some other process)

Questions:
1. What mechanism are you using to measure used memory on Linux?  top, ps, something else?
2. Are you seeing specific problems on your system (either Minecraft crashing with an OutOfMemoryError, or the Linux OOM killer killing off other processes due to lack of virtual memory) ?

The FTB Chunks client does make efforts to release the memory it allocates for constructing the map (which about 4MB per 512x512 region).  There are some client-side options (see the Advanced section) to tune this a little further. In particular, you can reduce the "Idle region release timeout" (default 300 seconds), and "Autorelease regions on map close" settings if you want to be more frugal with RAM, at the expense of more disk activity when region data needs to be accessed again.

**Comment by costelush41** [comment]
1.I am using an application called Stacer, I wanted to use this to monitor realtime ram usage with an user friendly interface while I am playing.
2. No, nothing at all.
3. I am using the recommended args by the AllTheMods team.

```-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true ```

**Comment by desht** [comment]
TBH if you're seeing any specific problem, I don't think there is a real problem here.  The FTB Chunks client is pretty memory hungry due to the amount of map data it needs to process, but steps have already been taken to reduce its memory usage, and I'm still looking at ways of reducing it more.

Not sure what else I can say here other than large numbers alone are not really a cause for concern.

**Comment by costelush41** [comment]
I am sure that there is a problem here, ram is getting hogged very fast if I play on any world, and the more I play the more ram is being used and then I really run into performance issues.

I really do not know what I could try to see the cause of this

**Comment by desht** [comment]
So why did you say "No, nothing at all." in answer to question 2?

**Comment by costelush41** [comment]
My apologies, I answered that because usually I close minecraft when notice performance issues, for example RAM was 29-30GB used out of 32. I could let it use the RAM until it crashes but I usually kill the process when I notice performance issues.

And Linux OOM didn't force close any of the tasks afaik, yet.

**Comment by desht** [comment]
Your JVM options don't include memory allocation, i.e. `-Xms` or `-Xmx`.  What are you passing for those values?

Again, Linux does not report memory in any way similar to Windows.  Seeing 29-30GB  of memory used does not mean your system is running out of memory, since that figure probably includes a lot of buffer and cache space, which is ejected when the system needs to allocate actual virtual memory to processes which need it.

```
$ free
              total        used        free      shared  buff/cache   available
Mem:       65792316    27015384     7359712      411708    31417220    37590044
Swap:      16777212        3844    16773368
```

My system has 64GB physical RAM, but you can see used is already at 27GB and free only at 7GB, and that's with just a web browser, discord and my IDE running - not even a Minecraft process.  Looks like a lot of memory used, but the system is perfectly fine.

You mentioned "performance issues", but you haven't supplied any data demonstrating that FTB Chunks is the cause of said issues, or even what those performance issues actually are...

**Comment by costelush41** [comment]
Im sorry again, the allocated amount of ram is -Xms512M -Xmx8G

In regards to the performance issues im noticing lower frames per second when I play for longer times.

I understand your theory and I have nothing to comment on that. I will leave minecraft hog my ram until something is crashing then, but this doesn't explain why the ram is still used for no reason after I close the game.

I have tried to search for the advanced option that you mentioned but i didn't find it. Most likely I was not looking at the right place.

**Comment by desht** [comment]
> this doesn't explain why the ram is still used for no reason after I close the game.

See my earlier comments on how Linux reports free memory:
> that figure probably includes a lot of buffer and cache space, which is ejected when the system needs to allocate actual virtual memory to processes which need it
