### ISSUE TITLE
[Feature Request] Allow for multiplayer quest design (it doesn't refresh)

### ISSUE THREAD

**Issue by Leclowndu93150** [FTBTeam/FTB-Mods-Issues#971]
### Mod

FTB Quests

### Description

Hello it would be cool to allow us to have multiplayer quest dev because the current one doesn't refresh automaticaly for every player and it's kinda annoying

### Describe alternatives you've considered

None

**Comment by Leclowndu93150** [comment]
> Not sure I understand this request.  Can you provide an example of what should work but currently doesn't?

When i create a quest, it won't show up to my Friend until i save it to the server using the button

**Comment by desht** [comment]
Sounds more like a bug, then - I'm sure that used to work properly.  What version of the mod are you using? I'll look into it.

**Comment by desht** [comment]
Updated: just tested on 1.20, and it's working as expected; if I create a quest with one player, it immediately appears in the quest book of another player.  There is a bug right now where it also opens the quest view panel for everyone, but that will be fixed in the next release (should only open for the player who created the quest).

**Comment by Leclowndu93150** [comment]
> Sounds more like a bug, then - I'm sure that used to work properly.  What version of the mod are you using? I'll look into it.

1.20.1 on Forge 47.1.3

**Comment by desht** [comment]
> What version of the **mod**

**Comment by Leclowndu93150** [comment]
> > What version of the **mod**

Well the latest one available
