### ISSUE TITLE
[Bug]: Can Open Experience Obelisk in Claimed Chunks

### ISSUE THREAD

**Issue by Aiidoneus** [FTBTeam/FTB-Mods-Issues#979]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-2001.2.2

### Forge / Fabric version

1.20.1-47.1.76

### Modpack & version

FTB Presents Direwolf20 1.20 1.2.0

### What issue are you having?

FTB Chunks does not protect interactions with the Experience Obelisk from the Experience Obelisk mod. This means players can go into the obelisk and take experience as the please. 

I am guessing the mod is not triggering an event that FTB Chunks looks for to block for claimed chunks? 

### Steps to reproduce

1. Have someone claim a chunk
2. They place an experience obelisk and put experience in it
3. Have player 2 right click and take the experience

Player 2 has stolen the experience!

**Comment by desht** [comment]
Yes, this is very much down to Experience Obelisk.  It opens its GUI purely client-side (from the clientside `Block#use()` method), meaning no server-side events are ever fired, so FTB Chunks has no way of protecting access.

This needs to be fixed in Experience Obelisk.  My suggestion to them would be to send a server->client packet requesting GUI opening from the serverside `Block#use()` method (which only gets called if the player is allowed to interact). The client should only open the GUI on receipt of that packet.
