### ISSUE TITLE
[Bug]: Bad server performance detectAndSendChanges()

### ISSUE THREAD

**Issue by bigenergy** [FTBTeam/FTB-Mods-Issues#99]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1605.3.5-build.69

### Forge / Fabric version

1.16.5-36.2.8

### What issue are you having?

Bad performance :((
https://spark.lucko.me/Z9SOatfsxn
![image](https://user-images.githubusercontent.com/17977139/139530809-ec70c60d-ebc2-4a98-9aa3-69a9cc9368d6.png)

### Steps to reproduce

15+ players on server

**Comment by LatvianModder** [comment]
This issue may be due to how complex your quests are set up, what modpack is that?

**Comment by desht** [comment]
I should note that modern versions of FTB Quests (1.19+) do not suffer from this issue due to the addition of the `DeferredInventoryDetection` class: https://github.com/FTBTeam/FTB-Quests/blob/main/common/src/main/java/dev/ftb/mods/ftbquests/util/DeferredInventoryDetection.java

This schedules a check to be run X ticks after a player inventory change (X is configurable in server config - 20 by default).  If multiple changes happen rapidly over the course of a few ticks, only one check will be done, and not more often than X ticks.

@bigenergy I see that you have a released an "FTB Quests Optimizations" mod which mixes into our classes and tweaks things.  This is entirely unnecessary for 1.19 and 1.20 (although arguably useful for 1.18 where the changes weren't applied).  But I'd ask - if you still have some concerns, please speak to me about them - I will respond to you.  Because I will also state that mixing into our classes like this is a terrible idea, prone to breakage at any time.  And when it breaks, it's us who will be getting tickets from upset players.

I'm also puzzled about your mixin into the `ItemTask` class, which doesn't actually achieve anything useful. Can you please explain what you're doing there?
